[project]
name = "csv-plot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.3.2",
    "pyqt6>=6.9.1",
    "pyqtgraph>=0.13.7",
]
