"""生成 src/_build_info.py，注入版本号与编译时间。

用法：
    python scripts/generate_build_info.py

由 build_exe_nuitka / build_exe_pyinstaller / build_exe_pyinstaller.bat /
build_win.py 在打包前自动调用，构建结束后由各脚本自动清理。
注意：请勿在开发环境手动执行后保留该文件，否则版本号与编译时间
会因陈旧数据而失去"单一源头"语义。
"""
import datetime
import pathlib
import tomllib


def main():
    root = pathlib.Path(__file__).resolve().parent.parent
    pyproject = root / "pyproject.toml"

    # 从 pyproject.toml 读取版本号
    try:
        with pyproject.open("rb") as f:
            version = tomllib.load(f)["project"]["version"]
    except (OSError, KeyError, tomllib.TOMLDecodeError) as e:
        raise SystemExit(f"ERROR: 无法从 pyproject.toml 读取 version 字段: {e}")

    build_time = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    target = root / "src" / "_build_info.py"
    target.write_text(
        f"# Auto-generated by scripts/generate_build_info.py\n"
        f"# DO NOT EDIT MANUALLY\n"
        f"__version__ = \"{version}\"\n"
        f"__build_time__ = \"{build_time}\"\n",
        encoding="utf-8",
    )
    print(f"Generated _build_info.py: version={version}, build_time={build_time}")


if __name__ == "__main__":
    main()
